### ISSUE TITLE
Search for contacts, any fields !

### ISSUE THREAD

**Issue by Sanix-Darker** [frankie-njie/Booky#1]
.....

**Comment by frankie-njie** [comment]
So I wanted to start the search functionality but I have a problem with the logic and where to start.....

- Firstly whether to put it in the app.post() function or in the app.get()
- Am also having Ideas on using an API to get the data from the data base then save on a new folder and access it from ther or even use the fetch() to access it

**Comment by Sanix-Darker** [comment]
Ok, 
For the first point @frankie-njie , basically a search is made using the GET method so let's go with the `api.get()` for now !
Mhhhh quite strange for the second point... there is no need to create another folder to do things like that, let me explain it to you in simple steps :
- When a user hit a character in the search bar
- You concatain in to a temporary string in the client side code and send that to the Backend on an endpoint that's going to look like this `/search?q=text` on your controller you're going to get that new text for each keystroke and find in your database for each field in the target collection... i don't know if you're understanding what am saying.... take this as an example to move forward with this issue : http://physalix.com/jquery-autocomplete-search-with-node-js-and-mongoose/

**Comment by frankie-njie** [comment]
I was thinking that i should just return the all the files in the database after the user has uploaded

**Comment by frankie-njie** [comment]
Mr Sanix i've implemented the search but now I have to use Ajax to display it.....
Je voulais que tu check le code voir si tu peux dir quelque chose...

**Comment by Sanix-Darker** [comment]
Nice nice !
Ok ok, i will check the code, but first, can you screenshare a demo of it working ?
You can do it with LOOM, the Chrome web extension and share the link in here !

**Comment by frankie-njie** [comment]
Okay voici le lein. https://www.loom.com/share/3ccec3ad054e4d1495be663cb68a6398

**Comment by frankie-njie** [comment]
So now I want to implement the suggestion box for the search bar to show......
For now it just return the object that hast the corresponding text that was searched....

**Comment by frankie-njie** [comment]
Yoo Mr Sanix
j'ai implemente' le search la
