### ISSUE TITLE
Add Pagination to general search page

### ISSUE THREAD

**Issue by frankie-njie** [frankie-njie/Booky#7]
To paginate all searched contacts that have been returned

**Comment by frankie-njie** [comment]
yo Mr sanix cest how ?

**Comment by Sanix-Darker** [comment]
Hello @frankie-njie am doing well, thank you, i hope you too !
So fro guidelines i promised ou, try to follow this as a Datatable server-side, you need to define `dataSrc` and `columns.data` - the following should work :
```javascript
var table = $('#example').DataTable({
    processing: true,
    serverSide: true,
    ajax: {
        url: "/viewreports",
        dataSrc: "reportList"
    },    
    columns: [ 
        { data : "reportID" },
        { data : "eBayUserID" },
        { data : "reportStatus" },
        { data : "summary" },
        { data : "lastUpdatedDate" },        
        { data : "createdDate" },        
        { data : "paypalLoginID" }
   ]     
}); 
```
on an empty table :
```html
<table id="example"></table>  
```
`dataSrc` to specify what the array holding row items is named (cause of "Cannot read property 'length' of undefined")
columns.data to map item properties to columns
